apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helloworld
  namespace: {{ .Values.Namespace }}
  labels:
    app: my-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-helloworld
  template:
    metadata:
      labels:
        app: my-helloworld
    spec:
      containers:
      - name: my-helloworld
        image: testcontainers/helloworld
